# Generated by Django 4.1.5 on 2023-03-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userdata',
        ),
    ]
