# Generated by Django 4.1.5 on 2023-03-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_user_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='birth',
            field=models.DateField(max_length=50),
        ),
    ]
