# Generated by Django 4.1.5 on 2023-03-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_userdata_birth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userdata',
            new_name='user_signup',
        ),
    ]
