# Generated by Django 4.1.5 on 2023-03-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_user_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_signup',
            new_name='user',
        ),
    ]
