# Generated by Django 4.1.5 on 2023-03-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_user_signup_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='data',
        ),
    ]
