# Generated by Django 4.1.5 on 2023-03-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_user_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
    ]
