# Generated by Django 4.1.5 on 2023-03-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
