# Generated by Django 4.1.5 on 2023-03-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_user_name_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='users',
        ),
    ]
