# Generated by Django 4.1.5 on 2023-03-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_user_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='harsh', max_length=50)),
                ('password', models.CharField(default='harsh', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
