# Generated by Django 4.1.5 on 2023-03-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_data_name_data_birth_data_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='birth',
            field=models.DateField(default='1/1/0000', max_length=50),
        ),
    ]
