# Generated by Django 4.1.5 on 2023-03-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_delete_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='null', max_length=50)),
                ('midlename', models.CharField(default='null', max_length=50)),
                ('lastname', models.CharField(default='null', max_length=50)),
                ('gender', models.CharField(default='null', max_length=50)),
                ('birth', models.DateField(default='1111/11/11', max_length=50)),
                ('email', models.CharField(default='null', max_length=50)),
                ('phone', models.CharField(default='null', max_length=10)),
                ('password', models.CharField(default='null', max_length=50)),
            ],
        ),
    ]
