# Generated by Django 4.1.5 on 2023-03-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_user_data_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='gender',
            field=models.CharField(max_length=50),
        ),
    ]
