# Generated by Django 4.1.5 on 2023-03-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_user_data_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='midlename',
            field=models.CharField(max_length=50),
        ),
    ]
