# Generated by Django 4.1.5 on 2023-04-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_user_data_midlename'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('heading', models.CharField(max_length=50)),
                ('news', models.CharField(max_length=10000)),
            ],
        ),
    ]
