# Generated by Django 4.1.5 on 2023-06-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_reporter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
