# Generated by Django 4.1.5 on 2023-06-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
