# Generated by Django 4.1.5 on 2023-07-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.ImageField(upload_to='img/%y'),
        ),
    ]
