# Generated by Django 4.1.5 on 2023-07-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_upload_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='heading',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='file',
            new_name='image',
        ),
    ]
